### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BassK**

### CODE REVIEW

**Comment by BassK** [comment]
Added reference to RODBC package in the "Relational Databases' section

**Comment by terrytangyuan** [comment]
Thanks but the ctv file is the one that needs to be updated first. README file is generated from the ctv file. See this guide for more details: https://github.com/terrytangyuan/ctv-databases/blob/master/CONTRIBUTING.md

**Comment by BassK** [comment]
> 
> 
> Thanks but the ctv file is the one that needs to be updated first. README file is generated from the ctv file. See this guide for more details: https://github.com/terrytangyuan/ctv-databases/blob/master/CONTRIBUTING.md

Thanks for the info. I am currently getting an error message when running ctv2md.R (see below).  I ran the file in RStudio and on the command line. I am working in Windows. 


> check_ctv_packages(ctvfile)
$`Packages in <info> but not in <packagelist>`
character(0)

$`Packages in <packagelist> but not in <info>`
[1] "neo4r"

$`Packages in <packagelist> but not in repos`
[1] "MonetDBLite" "pivot"

**Comment by terrytangyuan** [comment]
Could you push your changes on the ctv file and I'll see if I can reproduce?

**Comment by terrytangyuan** [comment]
Thank you!

**Comment by BassK** [comment]
> 
> 
> Thank you!

Do you know what was causing my .ctv file for show those error messages?  If so, how could I have resolved that issue?

**Comment by terrytangyuan** [comment]
I am not sure since I wasn’t able to reproduce the issue you encountered. Could you try the latest version on master branch?

**Pull request merged**
